import 'menu_item.dart';

final List<MenuItem> menuItems = [
  // Cheese Cake
  MenuItem(
    id: 'cc_1',
    name: 'New York Classic Cheesecake',
    category: 'Cheese Cake',
    price: 129,
    description: 'Rich, creamy classic New York style baked cheesecake with buttery graham crust.',
    tags: ['Veg', 'Bestseller'],
    offerText: 'BUY ANY 2 AND GET ₹30 OFF',
    imageUrl: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=600&auto=format&fit=crop&q=80',
  ),
  MenuItem(
    id: 'cc_2',
    name: 'Blueberry Cheesecake',
    category: 'Cheese Cake',
    price: 149,
    description: 'Smooth cream cheese cake topped with luscious sweet-tart blueberry compote.',
    tags: ['Veg', 'Bestseller'],
    offerText: 'BUY ANY 2 AND GET ₹30 OFF',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80',
  ),
  MenuItem(
    id: 'cc_3',
    name: 'Nutella Cheesecake',
    category: 'Cheese Cake',
    price: 159,
    description: 'Decadent cheesecake marbled and topped with creamy Italian Nutella spread.',
    tags: ['Veg', 'Contains nuts'],
    offerText: 'BUY ANY 2 AND GET ₹30 OFF',
    imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop&q=80',
  ),
  MenuItem(
    id: 'cc_4',
    name: 'Lotus Biscoff Cheesecake',
    category: 'Cheese Cake',
    price: 159,
    description: 'Creamy cheesecake infused with spiced Lotus Biscoff spread and cookie crumble.',
    tags: ['Veg'],
    offerText: 'BUY ANY 2 AND GET ₹30 OFF',
    imageUrl: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=600&auto=format&fit=crop&q=80',
  ),
  MenuItem(
    id: 'cc_5',
    name: 'Double Truffle Cheesecake',
    category: 'Cheese Cake',
    price: 159,
    description: 'Ultra-rich chocolate cheesecake layered with dark chocolate truffle ganache.',
    tags: ['Veg'],
    offerText: 'BUY ANY 2 AND GET ₹30 OFF',
    imageUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&auto=format&fit=crop&q=80',
  ),

  // Brownie
  MenuItem(
    id: 'br_1',
    name: 'Classic Brownie',
    category: 'Brownie',
    price: 99,
    description: 'Fudgy, dense chocolate brownie baked to perfection with a shiny crackly top.',
    tags: ['Veg', 'Bestseller'],
    offerText: 'BUY ANY 2 AND GET ₹30 OFF',
    imageUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&auto=format&fit=crop&q=80',
  ),
  MenuItem(
    id: 'br_2',
    name: 'Hot Brownie',
    category: 'Brownie',
    price: 110,
    description: 'Warm, gooey chocolate brownie served piping hot with molten chocolate center.',
    tags: ['Veg', 'Hot'],
    offerText: 'BUY ANY 2 AND GET ₹30 OFF',
    imageUrl: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=600&auto=format&fit=crop&q=80',
  ),
  MenuItem(
    id: 'br_3',
    name: 'Brownie with Ice Cream',
    category: 'Brownie',
    price: 119,
    description: 'Warm fudge brownie paired with a generous scoop of vanilla bean ice cream.',
    tags: ['Veg', 'Bestseller'],
    offerText: 'BUY ANY 2 AND GET ₹30 OFF',
    imageUrl: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=600&auto=format&fit=crop&q=80',
  ),

  // Bomboloni
  MenuItem(
    id: 'bm_1',
    name: 'Dark Chocolate Bomboloni',
    category: 'Bomboloni',
    price: 89,
    description: 'Italian filled donut stuffed generously with rich dark chocolate custard.',
    tags: ['Veg'],
    offerText: 'BUY ANY 2 AND GET ₹30 OFF',
    imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80',
  ),
  MenuItem(
    id: 'bm_2',
    name: 'Milk Chocolate Bomboloni',
    category: 'Bomboloni',
    price: 89,
    description: 'Soft fluffy Italian donut filled with creamy milk chocolate ganache.',
    tags: ['Veg'],
    offerText: 'BUY ANY 2 AND GET ₹30 OFF',
    imageUrl: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?w=600&auto=format&fit=crop&q=80',
  ),
  MenuItem(
    id: 'bm_3',
    name: 'Vanilla Bomboloni',
    category: 'Bomboloni',
    price: 110,
    description: 'Classic sugar-dusted donut filled with fragrant Madagascar vanilla bean pastry cream.',
    tags: ['Veg'],
    offerText: 'BUY ANY 2 AND GET ₹30 OFF',
    imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80',
  ),
  MenuItem(
    id: 'bm_4',
    name: 'Nutella Bomboloni',
    category: 'Bomboloni',
    price: 110,
    description: 'Fluffy golden fried donut oozing with authentic Nutella hazelnut filling.',
    tags: ['Veg', 'Contains nuts'],
    offerText: 'BUY ANY 2 AND GET ₹30 OFF',
    imageUrl: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?w=600&auto=format&fit=crop&q=80',
  ),

  // Pastries
  MenuItem(
    id: 'pa_1',
    name: 'Truffle Pastry',
    category: 'Pastries',
    price: 69,
    description: 'Layered chocolate sponge drenched in silky chocolate truffle.',
    tags: ['Veg'],
    offerText: 'BUY ANY TWO @ ₹119',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80',
  ),
  MenuItem(
    id: 'pa_2',
    name: 'Chocolate Pastry',
    category: 'Pastries',
    price: 69,
    description: 'Classic moist chocolate cake slice with soft chocolate cream.',
    tags: ['Veg', 'Bestseller'],
    offerText: 'BUY ANY TWO @ ₹119',
    imageUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&auto=format&fit=crop&q=80',
  ),
  MenuItem(
    id: 'pa_3',
    name: 'Blueberry Pastry',
    category: 'Pastries',
    price: 69,
    description: 'Vanilla sponge pastry layered with whipped cream and blueberry compote.',
    tags: ['Veg'],
    offerText: 'BUY ANY TWO @ ₹119',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80',
  ),
  MenuItem(
    id: 'pa_4',
    name: 'Red Velvet Pastry',
    category: 'Pastries',
    price: 69,
    description: 'Signature red velvet sponge with tangy cream cheese frosting.',
    tags: ['Veg'],
    offerText: 'BUY ANY TWO @ ₹119',
    imageUrl: 'https://images.unsplash.com/photo-1586788224321-2ef3223f7939?w=600&auto=format&fit=crop&q=80',
  ),
  MenuItem(
    id: 'pa_5',
    name: 'Black Forest Pastry',
    category: 'Pastries',
    price: 69,
    description: 'Traditional chocolate sponge with cherries, whipped cream and chocolate flakes.',
    tags: ['Veg'],
    offerText: 'BUY ANY TWO @ ₹119',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80',
  ),

  // Waffle
  MenuItem(
    id: 'wf_1',
    name: 'Chocolate Waffle',
    category: 'Waffle',
    price: 80,
    description: 'Crisp golden Belgian waffle drizzled with chocolate sauce.',
    tags: ['Veg'],
    offerText: 'BUY ANY 2 AND GET ₹20 OFF',
    imageUrl: 'https://images.unsplash.com/photo-1562376552-0d160a2f238d?w=600&auto=format&fit=crop&q=80',
  ),
  MenuItem(
    id: 'wf_2',
    name: 'Milk Chocolate Waffle',
    category: 'Waffle',
    price: 99,
    description: 'Freshly baked waffle coated with smooth melted milk chocolate.',
    tags: ['Veg'],
    offerText: 'BUY ANY 2 AND GET ₹20 OFF',
    imageUrl: 'https://images.unsplash.com/photo-1562376552-0d160a2f238d?w=600&auto=format&fit=crop&q=80',
  ),
  MenuItem(
    id: 'wf_3',
    name: 'Kit Kat Waffle',
    category: 'Waffle',
    price: 110,
    description: 'Crispy waffle topped with crushed Kit Kat fingers and chocolate glaze.',
    tags: ['Veg'],
    offerText: 'BUY ANY 2 AND GET ₹20 OFF',
    imageUrl: 'https://images.unsplash.com/photo-1562376552-0d160a2f238d?w=600&auto=format&fit=crop&q=80',
  ),
  MenuItem(
    id: 'wf_4',
    name: 'Nutella Waffle',
    category: 'Waffle',
    price: 149,
    description: 'Warm waffle slathered generously with thick Nutella spread.',
    tags: ['Veg', 'Contains nuts', 'Bestseller'],
    offerText: 'BUY ANY 2 AND GET ₹20 OFF',
    imageUrl: 'https://images.unsplash.com/photo-1562376552-0d160a2f238d?w=600&auto=format&fit=crop&q=80',
  ),
  MenuItem(
    id: 'wf_5',
    name: 'Biscoff Waffle',
    category: 'Waffle',
    price: 149,
    description: 'Golden waffle topped with Lotus Biscoff spread and crushed biscuit bits.',
    tags: ['Veg'],
    offerText: 'BUY ANY 2 AND GET ₹20 OFF',
    imageUrl: 'https://images.unsplash.com/photo-1562376552-0d160a2f238d?w=600&auto=format&fit=crop&q=80',
  ),

  // Mini Waffle
  MenuItem(
    id: 'mw_1',
    name: 'Classic Mini Waffle',
    category: 'Mini Waffle',
    price: 49,
    description: 'Bite-sized crispy mini waffle dusted with icing sugar and honey.',
    tags: ['Veg'],
    imageUrl: 'https://images.unsplash.com/photo-1562376552-0d160a2f238d?w=600&auto=format&fit=crop&q=80',
  ),
  MenuItem(
    id: 'mw_2',
    name: 'Dark Chocolate Mini Waffle',
    category: 'Mini Waffle',
    price: 60,
    description: 'Bite-sized mini waffles coated in rich dark chocolate.',
    tags: ['Veg'],
    imageUrl: 'https://images.unsplash.com/photo-1562376552-0d160a2f238d?w=600&auto=format&fit=crop&q=80',
  ),
  MenuItem(
    id: 'mw_3',
    name: 'White Wonder Mini Waffle',
    category: 'Mini Waffle',
    price: 60,
    description: 'Mini waffles drizzled with creamy white chocolate.',
    tags: ['Veg'],
    imageUrl: 'https://images.unsplash.com/photo-1562376552-0d160a2f238d?w=600&auto=format&fit=crop&q=80',
  ),

  // Muffin & Buns & Donuts
  MenuItem(
    id: 'mf_1',
    name: 'Choco-Chip Muffin',
    category: 'Muffin',
    price: 30,
    description: 'Fluffy dome-shaped bakery muffin loaded with melt-in-mouth choco-chips.',
    tags: ['Veg', 'Bestseller'],
    offerText: 'BUY 4 @ ₹99',
    imageUrl: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=600&auto=format&fit=crop&q=80',
  ),
  MenuItem(
    id: 'kb_1',
    name: 'Korean Cream Cheese Bun',
    category: 'Korean Bun',
    price: 40,
    description: 'Soft buttery bun soaked in garlic butter and filled with sweet cream cheese.',
    tags: ['Veg', 'Bestseller'],
    offerText: 'BUY 3 @ ₹99',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80',
  ),
  MenuItem(
    id: 'dn_1',
    name: 'Glazed Chocolate Donut',
    category: 'Donuts',
    price: 79,
    description: 'Ring donut dipped in glossy chocolate glaze and rainbow sprinkles.',
    tags: ['Veg', 'Bestseller'],
    offerText: 'BUY 2 @ ₹119',
    imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80',
  ),

  // Cold Coffee & Cafe
  MenuItem(
    id: 'cf_1',
    name: 'Classic Cold Coffee',
    category: 'Cold Coffee',
    price: 60,
    description: 'Blended creamy cold coffee with a rich frothy top.',
    tags: ['Veg', 'Cold', 'Bestseller'],
    imageUrl: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=600&auto=format&fit=crop&q=80',
  ),
  MenuItem(
    id: 'cf_2',
    name: 'Cold Coffee with Ice Cream',
    category: 'Cold Coffee',
    price: 70,
    description: 'Thick blended cold coffee topped with a scoop of vanilla ice cream and chocolate drizzle.',
    tags: ['Veg', 'Cold', 'Bestseller'],
    imageUrl: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=600&auto=format&fit=crop&q=80',
  ),
  MenuItem(
    id: 'cf_3',
    name: 'Brownie Shake',
    category: 'Cold Coffee',
    price: 80,
    description: 'Decadent thick milkshake blended with a fudgy chocolate brownie.',
    tags: ['Veg', 'Cold', 'Contains nuts'],
    imageUrl: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&auto=format&fit=crop&q=80',
  ),
];
